[auto-update]
enabled=1
last-check=2026-02-20
interval-in-days=7

[default]
meta=true
output_dir=output\
prefix_separator= - 
cookies_file=
cookies_from_browser=firefox
; cookies_from_browser=firefox:default-release
; cookies_from_browser=chrome:Profile 1

[meta]
url=true
title=true
channel=true
created=true
keywords=true
video_id=false
uploader=true
uploader_id=false
channel_id=false
duration=false
view_count=true
like_count=true
comment_count=true
tags=true
description=true
